project:
  type: website
  output-dir: docs

website:
  title: "Advanced Data Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: exercises.qmd
        text: Exercises

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full


