project:
  type: website
  output-dir: docs

website:
  title: "Advanced Data Science"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: schedule.qmd
        text: Schedule/Syllabus
      - href: exercises.qmd
        text: Exercises
      - href: homework.qmd
      - href: resources.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page-layout: full


