---
title: "Schedule"
editor: source
---

# Advanced Data Science I

## Week 1
- **Class 1:** [Intro](https://docs.google.com/presentation/d/1fb5W1fcnIdYtq_sXl6V3bh2uFdJ68h_qSwUxWtPs_to/edit?usp=sharing) and [Linux & Shell](https://docs.google.com/presentation/d/1kFjRsQ0tOaH59HNp-v5_xdmRvAfJM0uv3R3SS-RxT4I/edit?usp=sharing) – Present (intro, basics)  
- **Class 2:** [Linux & Shell - Practice](exercises/linux_shell.html) (hands-on commands)  

### Homework 1
- **Homework 1:**  [Homework 1](homework/hw1_shell_and_linux.html)

## Week 2
<!-- John -->
- **Class 3:** [SLURM and the Cluster](https://docs.google.com/presentation/d/1L8KgZ_my3Onj8COclq71cQxWP47MHZD1zTG5dHdUdMA/edit?usp=sharing)
- **Class 4:** [SLURM and the Cluster - Practice](exercises/slurm_and_the_cluster.html)

## Week 3 
<!-- Brian -->
- **Class 5:** [Power and Sample Size](https://docs.google.com/presentation/d/1Ym5S4LkMsUXSdE-CM-X-BMiGH2UthhNOrRh23bkYSOQ/edit?usp=sharing)
- **Class 6:** [Power – Practice](exercises/power.html)

## Week 4
<!-- John -->
- **Class 7:** [R packages](https://drive.google.com/file/d/17mLWgxBLnAXoRntMAiNYAm4JsqO12AUl/view?usp=sharing)
<!-- Brian -->
- **Class 8:** [Grants](https://docs.google.com/presentation/d/1kU4HcYdaVqkg7I3ZexhAse5AZG8dlxTEgfakOUvCIdo/edit?usp=sharing)

## Week 5
<!-- Both -->
- **Class 9:** Present P1 (see [Presentations](homework/presentation1.html))
<!-- John -->
- **Class 10:** [SQL Basics and Hurdles](https://docs.google.com/presentation/d/15bZFKubDeY5Mmj37j1p639h2uLMAxZzHW9gExUh2jcU/edit?slide=id.p#slide=id.p)  

## Week 6
<!-- John -->
- **Class 11:** [Data Visualization](https://docs.google.com/presentation/d/17RY0WNOqnsjiII_hE-T7ADP5fAGZdd6v56O8QEw7qhg/edit?usp=sharing) – Lecture  
<!-- John -->
- **Class 12:** [Data Visualization (EDA) – Application](exercises/data_viz.html)

## Week 7
<!-- John -->
- **Class 13:** (pushed from before) [SQL Basics and Hurdles](https://docs.google.com/presentation/d/15bZFKubDeY5Mmj37j1p639h2uLMAxZzHW9gExUh2jcU/edit?slide=id.p#slide=id.p)  
- **Class 14:** App Dashboard – Setup & Workflow

## Week 8
<!-- John -->
- **Class 15:** App Dashboard – Application
<!-- Both -->
- **Class 16:** Final Presentations  


# Advanced Data Science II

## Week 1
<!-- John - Prediction competition assignment -->
- **Class 1:** [Performance Metrics](https://docs.google.com/presentation/d/1oSBcOWzJ7rOvZJuxiEDOQRuEBp4ncucBeXF8DiHL8kY/edit?usp=sharing) Measurement & Models – Lecture  
<!-- Angela -->
- **Class 2:** [Tidymodels](https://docs.google.com/presentation/d/1DYL83AW0lNF1xAJlBiOxD-V9mfGKAm_3ixEeyoA-Ess/edit?usp=sharing)

## Week 2
<!-- Angela -->
- **Class 3:** [Tidymodels Workthrough](https://www.tidymodels.org/start/)
<!-- Brian  - NHANES project assignment -->
- **Class 4:** Prediction Competition – Presentation 

## Week 3
<!-- John -->
- **Class 5:** [Missing Data](https://docs.google.com/presentation/d/1_yN0OIDyloqqH4_Utk66KmiUhKHGIuwRl3rUvy1f5EE/edit?usp=sharing)
<!-- John -->
- **Class 6:** Missing Data – Application

## Week 4
<!-- Brian  - LLM project assignment -->
<!-- John -->
- **Class 7:** [APIs + Pulling](https://docs.google.com/presentation/d/1xVh29cZAKY01coRTcGOaPftpQn1_1LCdZhW_b7tnY18/edit?usp=sharing)
<!-- John -->
- **Class 8:** Language Models – API (overview, usage)  

## Week 5
<!-- John -->
- **Class 9:** Pipelining Techniques – Lecture  
<!-- John Assign targets pipeline project -->
- **Class 10:** Pipelining Techniques – Application  

## Week 6
<!-- Brian -->
- **Class 13:** Complex Data - Lecture
- **Class 14:** Complex Data - Application

## Week 7
<!-- Guest -->
<!-- Practical Bayes assignment -->
- **Class 11:** Practical Bayes – Guest Lecture 
- **Class 12:** Practical Bayes – Application


## Week 8
- **Class 15:** Presentation prep
- **Class 16:** Final Presentations (Data Applications)


